### ISSUE TITLE
Truncate to common data extent

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/cmip6-utils#24]
Some models native grids don't have data all the way out to extent of the common grid. We should adjust the cropping portion of the regridding to exclude these nodata cells, such that we have a consistent datacube of valid data values (compared among models within a given scenario)

**Comment by Joshdpaul** [comment]
@kyleredilla in light of your recent work on the grid selection, this issue is no longer a thing right?

**Comment by kyleredilla** [comment]
Yep, I think we're good here, good call!
