### ISSUE TITLE
Add E3SM data to the transfers pipeline

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/cmip6-utils#32]
Get the data for E3SM-1-0, or E3SM-2-0, into the standard transfers pipeline. Need to determine what version, first. E3SM-1-0 has more scenarios available, but -2-0 might have some significant improvements.

**Comment by kyleredilla** [comment]
Heard back from the ESGF mailing list, looks like ScenarioMIP data for the E3SM models is under /user_pub_work/CMIP6/ScenarioMIP/

<img width="798" alt="image" src="https://github.com/ua-snap/cmip6-utils/assets/29390510/6827c297-5f3f-4eb1-aad1-ff5a99e7b28d">

**Comment by Joshdpaul** [comment]
The E3SM collection of models was added to the transfers pipeline, and the files can be audited via Globus, but there is a permissions issue that needs to be resolved before we can actually transfer the data.

**Comment by Joshdpaul** [comment]
The permissions issue appears to have been resolved, and we now have E3SM data mirrored on ARDN.
