### ISSUE TITLE
Land/Ocean mask

### ISSUE THREAD

**Issue by Joshdpaul** [ua-snap/cmip6-utils#44]
Determine a common extent for land- or ocean-only variables, and apply the mask to these variables during regridding.

**Comment by kyleredilla** [comment]
Do we really want to consider a smaller extent for the land-only variables? I thought we agreed that for these few variables we would just retain the same -180-180°W, 50-90°N extent, to keep things consistent with the rest of the regridded data. 

As far as choosing a final mask, I think the natural choices for masks would what is used by models already on the target grid (CESM2, NorESM2-MM, TaiESM1). Here are some questions to consider when exploring this:
1. are the masks used for these models the same (within variables)?
2. are the source masks the same between terrestrial variables? Likewise but for ocean variables?

I don't think it matters much what the source masks are - we need to use them as we have seen from our exploration, but when a file is regridded, if there are any valid values that get masked off by the "production" mask(s), I think that is OK. we may want to know if that is the case though, and likewise if there are any nodata pixels that wind up outside of the production mask(s) (i.e., nodata in the source, but is actually considered a valid data pixel in the target)
