### ISSUE TITLE
Drop MPI-ESM1-2-LR

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/cmip6-utils#55]
We are dropping this model in favor of the -HR version

See the [SNAP doc on model selection ](https://docs.google.com/document/d/19ZL6arJCv5mpjIXVZUbuasZvEh_dOEc2iN6BFY3mM8s/edit?usp=sharing)for more info

**Comment by Joshdpaul** [comment]
This model is still included in the audit, but is no longer included in `transfers/config.prod_variant_lu` and will therefore not be transferred.
